# Numpy Tutorial
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.  

This is a tutorial for the basics of numpy. Numpy is basically a very powerful and fast module for processing computations involving very large and multidimensional arrays. It will help you kick start your calculations in numpy and be able to execute them with ease. However, this is not an exhaustive course and learners are required to study further and experiment with Numpy **themselves** to get a deeper understanding of the module.

To install Numpy module using pip in Ubuntu, we can use this command on the terminal:<br/>
*sudo pip install numpy*

In [1]:
import numpy as np
import sys
from IPython.display import display

print("Using python path ", sys.executable)

Using python path  /home/lt144/Documents/anaconda3/bin/python


## Creating a 1-D array Numpy Array
We can simply pass a list parameter to the np.array() function and it will return a corresponding numpy array. Additionally, we can use Python's built-in **type** funtion to verify this.

In [2]:
a = np.array([15, 20, 45, -37, 13])
print(a)
print("The variable a is of type: ", type(a))

[ 15  20  45 -37  13]
The variable a is of type:  <class 'numpy.ndarray'>


Well, we can also convert a previous list to a  numpy array.

In [3]:
my_list = [15, 20, 45, -37, 13]
b = np.array(my_list)
print(my_list)
print("Type: ", type(my_list))
print(b)
print("Type: ", type(b))

[15, 20, 45, -37, 13]
Type:  <class 'list'>
[ 15  20  45 -37  13]
Type:  <class 'numpy.ndarray'>


## Shape of 1-D Numpy Array
The shape of a 1-D numpy array can be obtained by using the python's **len** funtion. However, we can also use shape funtion; this returns a somewhat different output. We will get back to that later.

In [4]:
print(len(a))
print(a.shape)

5
(5,)


## Slicing : Selecting Elements of 1-D Numpy Array
The index of numpy array starts with 0 up to the length of the array-1. We can select an element of a numpy array using the variable name with **square [ ]** brackets.

In [5]:
print("The 1st element of the array is: ", a[0])
print("The 2nd element of the array is: ", a[1])
print("The last element of the array is:", a[len(a)-1])

The 1st element of the array is:  15
The 2nd element of the array is:  20
The last element of the array is: 13


Now, I am curious. What if we input a negative number in the indexing?? Well, it just works.<br/>
The output will be similar to taking the **last** element when **-1** is input, **second last** element when **-2** is input ... nth last element when -n is input. 

In [6]:
print("The last element of the array is:", a[-1])
print("The last element of the array is:", a[-2])

The last element of the array is: 13
The last element of the array is: -37


But what about selecting multiple elements from the 1-D Array at a time? Well, we can do that as well using the **colon :** symbol. We just have to provide the index from where we want to **start** to the index where we want to **end+1**. This is similar to the Python's built-in function **range** where, similar to the last index, the last number is neglected in the output.

Whatever way we choose to input the index, the output will remain of type **numpy array** even if there is only 1 element in it.

In [7]:
print(a[0:3])
print("The output is of type", type(a[0:3]))
print(a[2:3])
print("The output is of type", type(a[2:3]))

[15 20 45]
The output is of type <class 'numpy.ndarray'>
[45]
The output is of type <class 'numpy.ndarray'>


But we are **LAZY!!!**. Why can't we just provide **1 input** index with the colon operator to output something? Well, in Numpy, we can. (Makes us believe that the writers of this module were as lazy as us.... to some extent.) The output will be:
* All elements **after the specified index** if we choose **[n:]**
* All elements **before the specified index** if we choose **[:n]**.
* All elements **after the nth last specified index** if we choose **[-n:]**
* All elements **before the nth last specified index** if we choose **[:-n]**

So, let's try this lazy method. Let's recalll our numpy array.

In [8]:
print(a)

[ 15  20  45 -37  13]


In [9]:
print("Input only after colon:")
print(a[:0])
print(a[:2])
print(a[:5])

Input only after colon:
[]
[15 20]
[ 15  20  45 -37  13]


In [10]:
print("Input only before the colon:")
print(a[0:])
print(a[1:])
print(a[2:])

Input only before the colon:
[ 15  20  45 -37  13]
[ 20  45 -37  13]
[ 45 -37  13]


In [11]:
print("Negative Input only after the colon:")
print(a[:-1])
print(a[:-3])

Negative Input only after the colon:
[ 15  20  45 -37]
[15 20]


In [12]:
print("Negative Input only before the colon:")
print(a[-3:])
print(a[-5:])

Negative Input only before the colon:
[ 45 -37  13]
[ 15  20  45 -37  13]


Now, I am curious again. What if we input a negative number in above expressions or if we use a value longer than the length of the array?? <br/>
Well, it turns out

In [13]:
a[-6:]

array([ 15,  20,  45, -37,  13])

## Creating n-D Numpy array
Similar to creating a 1d numpy array, we can pass **nested lists** i.e. list of lists as a parameter to the function np.array(). An n-dimensional array will be created corresponding to the passed parameter. We also see that the **type** of the n-dimensional array is same as that of previously created.

In [14]:
nested_list = [[21, 22], [43, 44], [56, 57]]
b = np.array(nested_list)
print(b)
print("The variable b is of type:", type(b))

[[21 22]
 [43 44]
 [56 57]]
The variable b is of type: <class 'numpy.ndarray'>


## Shape of n-D Numpy array
The shape of the n-dimensional numpy array can be found using the shape method of the array similar to that of the 1-d array. The shape method outputs a tuple that represents the shape of the array which can be verified using our friendly neighbourhood **type** function. There is a catch, however, when using the python's built-in **len** function. Give it a try! 

In [15]:
print(b.shape)
print("The type of the output using the SHAPE method is :", type(b.shape))
print(len(b))

(3, 2)
The type of the output using the SHAPE method is : <class 'tuple'>
3


## Selecting Elements of n-D Numpy array
Selecting the element of an n-dimensional array is somewhat different from that in 1-dimensional array because simply using b[ ] will give a different output. Let's try that first. We first print the array itself for easier reference.

In [16]:
print(b)
print()
print("The [0]th index gives", b[0])
print("The [1]th index gives", b[1])
print("The [2]th index gives", b[2])

[[21 22]
 [43 44]
 [56 57]]

The [0]th index gives [21 22]
The [1]th index gives [43 44]
The [2]th index gives [56 57]


We can see that using only one square bracket outputs the **row** of the array corresponding to the index provided. So, let's try using **two** square brackets, because, why not??

In [17]:
print(b)
print()
print(b[0][1])
print("Eureka!! It works!!!. Let's try some more.")
print()
for i in range(b.shape[0]):
    for j in range(b.shape[1]):
        print("The [{}][{}] th index gives: {}".format(i, j, b[i][j]))

[[21 22]
 [43 44]
 [56 57]]

22
Eureka!! It works!!!. Let's try some more.

The [0][0] th index gives: 21
The [0][1] th index gives: 22
The [1][0] th index gives: 43
The [1][1] th index gives: 44
The [2][0] th index gives: 56
The [2][1] th index gives: 57


## Numpy in-built funcitons

### np.arange()
arange not **arrange** is used to generate number between certain range.

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0,10,3)

array([0, 3, 6, 9])

### np.zeros()
Used to create an numpy array with it's element as zeros.

In [20]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

We can even have zeros array with more than 1 dimension

In [21]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

**Note: ** zeros takes the dimension as a single input, so we must provide the dimension as a **Tuple**, such as np.zeros(**(5,5)**) instead of np.zeros**(5,5)**

### np.ones()
If we can have zeros, why not one's?

In [22]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [23]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

### np.eye()

Gives us an identity matirx

In [24]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

### np.linspace()

Similar to arange(), but outputs an array with the desired number of elements inside that range

In [25]:
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

### np.random.rand()

Create a random array between range 0 to 1

In [26]:
np.random.rand(5)

array([ 0.09989991,  0.81306285,  0.42558028,  0.14355839,  0.84582172])

In [27]:
np.random.rand(5)

array([ 0.15598616,  0.95131875,  0.27343396,  0.21615143,  0.4706745 ])

### np.random.randn()

In [28]:
np.random.randn(5)

array([ 0.64534331, -0.39842771, -0.05650366, -0.81176533, -0.21252162])

In [29]:
np.random.randn(5,5)

array([[-0.06829737, -0.60191436, -0.53064869, -0.67024857,  0.78472267],
       [-0.08185194, -0.37967527, -1.11393004, -0.96595738,  1.5469334 ],
       [ 0.31053427, -0.80491906,  1.05807953, -1.98581907,  0.81526881],
       [-0.44385603, -1.04392847,  0.47741661,  0.33864005,  0.63073836],
       [-0.18191218,  1.07877991,  2.06581348,  0.98986416, -0.69140437]])

### np.random.randint()
Gives a random integer from the range

In [30]:
np.random.randint(0, 50)

27

In [31]:
np.random.randint(0, 50, 10)

array([28, 29,  8, 44, 48,  6, 41,  9, 37, 13])

### np.reshape()
Used to reshape the array into desired shape

In [32]:
arr = np.arange(0,25)
print(arr)
print('Array Shape: ',arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Array Shape:  (25,)


In [33]:
arr = arr.reshape(5,5)
print(arr)
print('Array Shape: ',arr.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Array Shape:  (5, 5)


**Note: ** while reshaping we need to include all the elements in the new rows and columns else we get an error

In [34]:
arr2 = np.arange(0, 25)
arr2.reshape(3,5)

ValueError: cannot reshape array of size 25 into shape (3,5)

In [35]:
arr = np.random.randint(0, 50, 10)
arr

array([15, 36,  3, 38, 28, 33, 11, 26, 12, 46])

In [36]:
arr.max(), arr.argmax()

(46, 9)

### Vectorizaiton
We need to convert the 1 D array into either a column vector or row vector.
* A column vector is a **N X 1 ** matrix
* A row vector is a **1 X N** matrix

In [37]:
arr = np.random.randint(0, 50, 10)
arr

array([27, 24, 38, 37, 32,  6, 22, 15,  4,  6])

In [38]:
arr.shape

(10,)

In [39]:
# row vector
arr.reshape(1,10)

array([[27, 24, 38, 37, 32,  6, 22, 15,  4,  6]])

In [40]:
arr.reshape(1,10).shape

(1, 10)

In [41]:
#column vector
arr.reshape(10,1)

array([[27],
       [24],
       [38],
       [37],
       [32],
       [ 6],
       [22],
       [15],
       [ 4],
       [ 6]])

In [42]:
arr.reshape(10,1).shape

(10, 1)

## matrix operations

In [85]:
a = np.arange(0, 24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [84]:
b = np.arange(0, 48, 2).reshape(4,6)
b

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46]])

In [90]:
np.multiply(a,b)

array([[   0,    2,    8,   18,   32,   50],
       [  72,   98,  128,  162,  200,  242],
       [ 288,  338,  392,  450,  512,  578],
       [ 648,  722,  800,  882,  968, 1058]])

### np.add()
add two matrices

In [71]:
np.add(a,b)

array([[ 0,  3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30, 33],
       [36, 39, 42, 45, 48, 51],
       [54, 57, 60, 63, 66, 69]])

### np.subtract()
subtract two matrices

In [72]:
np.subtract(a,b)

array([[  0,  -1,  -2,  -3,  -4,  -5],
       [ -6,  -7,  -8,  -9, -10, -11],
       [-12, -13, -14, -15, -16, -17],
       [-18, -19, -20, -21, -22, -23]])

In [73]:
a*b

array([[   0,    2,    8,   18,   32,   50],
       [  72,   98,  128,  162,  200,  242],
       [ 288,  338,  392,  450,  512,  578],
       [ 648,  722,  800,  882,  968, 1058]])

In [74]:
b*a

array([[   0,    2,    8,   18,   32,   50],
       [  72,   98,  128,  162,  200,  242],
       [ 288,  338,  392,  450,  512,  578],
       [ 648,  722,  800,  882,  968, 1058]])

### np.matmul()
matrix multiplicaiton of matrices

In [75]:
b = np.arange(0, 48, 2).reshape(6,4)
b

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [76]:
np.matmul(a,b)

array([[ 440,  470,  500,  530],
       [1160, 1262, 1364, 1466],
       [1880, 2054, 2228, 2402],
       [2600, 2846, 3092, 3338]])

In [77]:
np.matmul(b,a)

array([[ 168,  180,  192,  204,  216,  228],
       [ 456,  500,  544,  588,  632,  676],
       [ 744,  820,  896,  972, 1048, 1124],
       [1032, 1140, 1248, 1356, 1464, 1572],
       [1320, 1460, 1600, 1740, 1880, 2020],
       [1608, 1780, 1952, 2124, 2296, 2468]])

In [78]:
np.square(a)

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256, 289],
       [324, 361, 400, 441, 484, 529]])

In [79]:
a**2

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256, 289],
       [324, 361, 400, 441, 484, 529]])

In [80]:
np.sqrt(a)

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
         2.23606798],
       [ 2.44948974,  2.64575131,  2.82842712,  3.        ,  3.16227766,
         3.31662479],
       [ 3.46410162,  3.60555128,  3.74165739,  3.87298335,  4.        ,
         4.12310563],
       [ 4.24264069,  4.35889894,  4.47213595,  4.58257569,  4.69041576,
         4.79583152]])

In [81]:
a**.5

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
         2.23606798],
       [ 2.44948974,  2.64575131,  2.82842712,  3.        ,  3.16227766,
         3.31662479],
       [ 3.46410162,  3.60555128,  3.74165739,  3.87298335,  4.        ,
         4.12310563],
       [ 4.24264069,  4.35889894,  4.47213595,  4.58257569,  4.69041576,
         4.79583152]])