# Numpy Tutorial
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.  

This is a tutorial for the basics of numpy. Numpy is basically a very powerful and fast module for processing computations involving very large and multidimensional arrays. It will help you kick start your calculations in numpy and be able to execute them with ease. However, this is not an exhaustive course and learners are required to study further and experiment with Numpy **themselves** to get a deeper understanding of the module.

To install Numpy module using pip in Ubuntu, we can use this command on the terminal:<br/>
*sudo pip install numpy*

In [25]:
import numpy as np
import sys
from IPython.display import display

print("Using python path ", sys.executable)

Using python path  /home/lt-134/.conda/envs/ds1/bin/python


## Creating a 1-D array Numpy Array
We can simply pass a list parameter to the np.array() function and it will return a corresponding numpy array. Additionally, we can use Python's built-in **type** funtion to verify this.

In [66]:
a = np.array([15, 20, 45, -37, 13])
print(a)
print("The variable a is of type: ", type(a))

[ 15  20  45 -37  13]
The variable a is of type:  <class 'numpy.ndarray'>


## Shape of 1-D Numpy Array
The shape of a 1-D numpy array can be obtained by using the python's **len** funtion. However, we can also use shape funtion; this returns a somewhat different output. We will get back to that later.

In [67]:
print(len(a))
print(a.shape)

5
(5,)


## Slicing : Selecting Elements of 1-D Numpy Array
The index of numpy array starts with 0 up to the length of the array-1. We can select an element of a numpy array using the variable name with **square [ ]** brackets.

In [69]:
print("The 1st element of the array is: ", a[0])
print("The 2nd element of the array is: ", a[1])
print("The last element of the array is:", a[len(a)-1])

The 1st element of the array is:  15
The 2nd element of the array is:  20
The last element of the array is: 13


Now, I am curious. What if we input a negative number in the indexing?? Well, it just works.<br/>
The output will be similar to taking the **last** element when **-1** is input, **second last** element when **-2** is input ... nth last element when -n is input. 

In [93]:
print("The last element of the array is:", a[-1])
print("The last element of the array is:", a[-2])

The last element of the array is: 13
The last element of the array is: -37


But what about selecting multiple elements from the 1-D Array at a time? Well, we can do that as well using the **colon :** symbol. We just have to provide the index from where we want to **start** to the index where we want to **end+1**. This is similar to the Python's built-in function **range** where, similar to the last index, the last number is neglected in the output.

Whatever way we choose to input the index, the output will remain of type **numpy array** even if there is only 1 element in it.

In [79]:
print(a[0:3])
print("The output is of type", type(a[0:3]))
print(a[2:3])
print("The output is of type", type(a[2:3]))

[15 20 45]
The output is of type <class 'numpy.ndarray'>
[45]
The output is of type <class 'numpy.ndarray'>


But we are **LAZY!!!**. Why can't we just provide **1 input** index with the colon operator to output something? Well, in Numpy, we can. (Makes us believe that the writers of this module were as lazy as us.... to some extent.) The output will be:
* All elements **after the specified index** if we choose **[n:]**
* All elements **before the specified index** if we choose **[:n]**.
* All elements **after the nth last specified index** if we choose **[-n:]**
* All elements **before the nth last specified index** if we choose **[:-n]**

So, let's try this lazy method.

In [111]:
print("Input only after colon:")
print(a[:0])
print(a[:2])
print(a[:5])
print()
print("Input only before the colon:")
print(a[0:])
print(a[1:])
print(a[2:])
print()
print("Negative Input only after the colon:")
print(a[:-1])
print(a[:-3])
print()
print("Negative Input only before the colon:")
print(a[-3:])
print(a[-5:])

Input only after colon:
[]
[15 20]
[ 15  20  45 -37  13]

Input only before the colon:
[ 15  20  45 -37  13]
[ 20  45 -37  13]
[ 45 -37  13]

Negative Input only after the colon:
[ 15  20  45 -37]
[15 20]

Negative Input only before the colon:
[ 45 -37  13]
[ 15  20  45 -37  13]


Now, I am curious again. What if we input a negative number in above expressions or if we use a value longer than the length of the array?? <br/>
Well, it turns out

In [95]:
a[-2:]

array([-37,  13])

## Creating n-D Numpy array
Similar to creating a 1d numpy array, we can pass **nested lists** i.e. list of lists as a parameter to the function np.array(). An n-dimensional array will be created corresponding to the passed parameter. We also see that the **type** of the n-dimensional array is same as that of previously created.

In [49]:
nested_list = [[21, 22], [43, 44], [56, 57]]
b = np.array(nested_list)
print(b)
print("The variable b is of type:", type(b))

[[21 22]
 [43 44]
 [56 57]]
The variable b is of type: <class 'numpy.ndarray'>


## Shape of n-D Numpy array
The shape of the n-dimensional numpy array can be found using the shape method of the array similar to that of the 1-d array. The shape method outputs a tuple that represents the shape of the array which can be verified using our friendly neighbourhood **type** function. There is a catch, however, when using the python's built-in **len** function. Give it a try! 

In [54]:
print(b.shape)
print("The type of the output using the SHAPE method is :", type(b.shape))
print(len(b))

(3, 2)
The type of the output using the SHAPE method is : <class 'tuple'>
3


## Selecting Elements of n-D Numpy array
Selecting the element of an n-dimensional array is somewhat different from that in 1-dimensional array because simply using b[ ] will give a different output. Let's try that first. We first print the array itself for easier reference.

In [58]:
print(b)
print()
print("The [0]th index gives", b[0])
print("The [1]th index gives", b[1])
print("The [2]th index gives", b[2])

[[21 22]
 [43 44]
 [56 57]]

The [0]th index gives [21 22]
The [1]th index gives [43 44]
The [2]th index gives [56 57]


We can see that using only one square bracket outputs the **row** of the array corresponding to the index provided. So, let's try using **two** square brackets, because, why not??

In [61]:
print(b)
print()
print(b[0][1])
print("Eureka!! It works!!!. Let's try some more.")
print()
for i in range(b.shape[0]):
    for j in range(b.shape[1]):
        print("The [{}][{}] th index gives: {}".format(i, j, b[i][j]))

[[21 22]
 [43 44]
 [56 57]]

22
Eureka!! It works!!!. Let's try some more.

The [0][0] th index gives: 21
The [0][1] th index gives: 22
The [1][0] th index gives: 43
The [1][1] th index gives: 44
The [2][0] th index gives: 56
The [2][1] th index gives: 57
